### ISSUE TITLE
Warn in case of missing / unknown keys

### ISSUE THREAD

**Issue by finestructure** [finestructure/Rester#10]
```
requests:

  contract_list:
    request:
      url: ${api_url}/v1/contract
    headers:
      Authorization: Bearer ${login.json.access_token}
    query:
      sort_by: cost
    validation:
      statuc: 200
      json:
        0:
          cost: 10
        1:
          cost: 20
        2:
          cost: 10
```

- typo (`statuc`)
- values (2.cost == 30)
