### ISSUE TITLE
Crash when referencing into list without entries

### ISSUE THREAD

**Issue by finestructure** [finestructure/Rester#39]
```
  product_list:
    url: ${api_url}/v1/contract
    headers:
      Authorization: Bearer ${login.access_token}
    validation:
      status: 200
      json:
        0:
          id: .regex(\w{8}-\w{4}-\w{4}-\w{4}-\w{12})
    log: json[0].id
```

```
 !  ~/Desktop  rester product.yml
🚀  Resting product.yml ...

🎬  login started ...

✅  login PASSED (0.777s)

🎬  product_list started ...

fish: 'rester product.yml' terminated by signal SIGILL (Illegal instruction)
```

```
  product_list:
    url: ${api_url}/v1/contract
    headers:
      Authorization: Bearer ${login.access_token}
    validation:
      status: 200
    log: json
```

```
 !  ~/Desktop  rester product.yml
🚀  Resting product.yml ...

🎬  login started ...

✅  login PASSED (1.122s)

🎬  product_list started ...

JSON: []

✅  product_list PASSED (0.176s)

Executed 2 tests, with 0 failures
```
