### ISSUE TITLE
Check same request name behaviour

### ISSUE THREAD

**Issue by finestructure** [finestructure/Rester#74]
I believe the following will silently overwrite the first request and run only once:

```
  document:
    url: ${api_url}/v1/contract/${contract_list[0].id}/document
    method: POST
    headers:
      Authorization: Bearer ${login.access_token}
    body:
      json:
        filename: vbox.png
        index: 8
    validation:
      status: 201

  document:
    url: ${api_url}/v1/contract/${contract_list[0].id}/document
    method: POST
    headers:
      Authorization: Bearer ${login.access_token}
    body:
      json:
        filename: vbox.png
        index: 9
    validation:
      status: 201
```

This must fail or at least warn about the duplicate key.
