### ISSUE TITLE
Deal with string/int conversion when validating variables

### ISSUE THREAD

**Issue by finestructure** [finestructure/Rester#78]
```
  contacts:
    url: ${api_url}/contacts/
    validation:
      status: 200
      json:
        # contacts are listed in reverse order or creation
        1:
          user: ${alice data.id}
```

The db field is an integer while the resolved variable substitution comes in as a string, leading to a failure:

```
❌  contacts FAILED : json invalid: index '1' validation error: key 'user' validation error: (2) is not equal to ("2")
```

**Comment by finestructure** [comment]
Workaround:

```
  contacts:
    url: ${api_url}/contacts/
    validation:
      status: 200
      json:
        # contacts are listed in reverse order or creation
        1:
          user: .regex(${alice data.id})
```
