### ISSUE TITLE
Allow variable substitution in `variables` section

### ISSUE THREAD

**Issue by finestructure** [finestructure/Rester#81]
For example, this should work if `TEST_ID` is an environment variable:

```
variables:
  email: foo-${TEST_ID}@bar.com
```

Currently, as a workaround, `TEST_ID` needs to be injected in `requests`, i.e.:

```
variables:
  username: foo
  domain: bar.com
requests:
  ...
  body:
    json:
      email: ${username}-${TEST_ID}@${domain}
```
