### ISSUE TITLE
Allow variable declaration in requests

### ISSUE THREAD

**Issue by finestructure** [finestructure/Rester#82]
This should work:

```
request:
  example:
    ...
    variables:
      doc_id: json.id
```

Currently, the id can only be referenced via `example.id` and not be redeclared.
