### ISSUE TITLE
Query parameters?

### ISSUE THREAD

**Issue by finestructure** [finestructure/Rester#95]
I can't believe this is the case but apparently I'm stripping off query parameters somewhere:

```
requests:
    test:
        url: "http://httpbin.org/anything?foo=bar"
        validation:
            status: 200
        log: json
```

results in:

```
🎬  test started ...

JSON: ["url": "http://httpbin.org/anything", "json": null, "method": "GET", "origin": "195.12.50.238", "form": [:], "data": "", "headers": ["Host": "httpbin.org", "User-Agent": "rester (unknown version) CFNetwork/1125.2 Darwin/19.4.0 (x86_64)", "Accept": "*/*", "Accept-Language": "en-gb", "Accept-Encoding": "gzip, deflate", "X-Amzn-Trace-Id": "Root=1-5ea95d5d-d343e690f115969c2b4ca184"], "files": [:], "args": [:]]
```

**Comment by finestructure** [comment]
Well, actually it's supported, just not in an obvious way 😅 

```
requests:
  repos:
    url: ${api_url}/projects/${project_id}/pipelines
    query:
      status: running
      page: 1
      per_page: 20
```
